UPDATE CM_INTERFACCIA_DOCUMENTO SET COD_DOCUMENTO = "01", DATA_ULTIMA_MODIFICA = DATE("2017-01-31") WHERE  ID_DOCUMENTO = 1;
UPDATE CM_INTERFACCIA_DOCUMENTO SET COD_DOCUMENTO = "02", DATA_ULTIMA_MODIFICA = DATE("2017-03-31") WHERE  ID_DOCUMENTO = 2;
UPDATE CM_INTERFACCIA_DOCUMENTO SET COD_DOCUMENTO = "03", DATA_ULTIMA_MODIFICA = DATE("2017-09-31") WHERE  ID_DOCUMENTO = 3;
UPDATE CM_INTERFACCIA_DOCUMENTO SET COD_DOCUMENTO = "04", DATA_ULTIMA_MODIFICA = DATE("2017-12-31") WHERE  ID_DOCUMENTO = 4;
